language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"

branches:
  only:
    - master

notifications:
  email:
    - hanno@hannosch.eu

install:
    - python -c "import re; print(re);"

script:
    - python dev.py
    - bin/test
