language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"

branches:
  only:
    - master

notifications:
  email:
    - hanno@hannosch.eu

install:
    - dpkg -l
    - deactivate
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then /usr/bin/pypy dev.py; fi
    - if [[ $TRAVIS_PYTHON_VERSION <> 'pypy' ]]; then /usr/bin/python$TRAVIS_PYTHON_VERSION dev.py; fi

script:
    - bin/test
