language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"

branches:
  only:
    - master

notifications:
  email:
    - hanno@hannosch.eu

script:
    - deactivate
    - /usr/bin/python$TRAVIS_PYTHON_VERSION dev.py
    - bin/test
