language: python
env:
    - PYTHON_VER=2.6
    - PYTHON_VER=2.7
    - PYTHON_VER=3.2

branches:
  only:
    - master

notifications:
  email:
    - hanno@hannosch.eu
    - buildout-development@googlegroups.com

install:
    - deactivate
    - make build

script: make test
